### ISSUE TITLE
If multiple buy transactions in less than 15 s

### ISSUE THREAD

**Issue by guillaumepalayer** [Betoken/angular-ui#10]
* 1st transaction is waiting to be mined.
* user closes the waiting panel.
* user display again the buy panel to trigger a second buy order.
* buy panel is replaced by the confirmation UI of the first tx. That mustn't occur in the user flow. 
It's a great example demonstrating why we need the notifications panel next to the logo.
FYI: we must keep the confirmation panel if just one tx is triggered. Actual UI is good. It's just not displayed at the right time during specific user flow like the aforementioned multiBuyTx' user flow.
@skrishnan99

**Comment by skrishnan99** [comment]
I will release an update by tomorrow with a fix

**Comment by skrishnan99** [comment]
fixed this bug
